name: Run Tests and Deploy

on:
  push:
    branches-ignore:
      - "dependabot/**" # avoid duplicates: only run the PR, not the push
      - "renovate/**" # avoid duplicates: only run the PR, not the push
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group: {}

permissions: {}

jobs:
  Default-cache-pnpm-first:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - name: Install pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        with:
          cache: true
          run_install: |
            args: [--prefer-frozen-lockfile]
      - name: Do stuff!
        run: pnpm wrangler --version
