name: Run Tests and Deploy New Cache
#Seems overly complex with no real benifit?

on:
  push:
    branches-ignore:
      - "dependabot/**" # avoid duplicates: only run the PR, not the push
      - "renovate/**" # avoid duplicates: only run the PR, not the push
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests-and-deploy:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
          package-manager-cache: false
      - name: Determine pnpm cache config
        id: cache-config
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        name: Restore pnpm cache
        id: cache-restore
        with:
          path: ${{ steps.cache-config.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache
      - name: Install dependencies
        run: pnpm install --prefer-frozen-lockfile
      - name: Do stuff!
        run: pnpm wrangler --version
      - name: Prune cache
        if: github.ref_name == github.event.repository.default_branch && steps.cache-restore.outputs.cache-hit != 'true'
        run: pnpm store prune
      - name: Save cache on default branch
        if: always() && github.ref_name == github.event.repository.default_branch && steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          path: ${{ steps.cache-config.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
